kind = "api"
previewPath = "/api" # TODO - should be excluded from preview in the first place
title = "API Server"
version = "1.0.0"
id = "3B4_FFSkEVBkAeYMFRJ2e"

[[services]]
localPort = 8080
name = "API Server"
paths = ["/api"]

[services.development]
run = "bash -c 'cd /home/runner/workspace && python artifacts/flask-api/app.py'"

[services.env]
PORT = "8080"

[services.production]

[services.production.build]
args = ["echo", "no-build-step"]

[services.production.run]
args = ["gunicorn", "--chdir", "artifacts/flask-api", "-w", "2", "-b", "0.0.0.0:8080", "app:app"]

[services.production.run.env]
PORT = "8080"

[services.production.health.startup]
path = "/api/healthz"
