"""Initial migration

Revision ID: 3215f2e07c9e
Revises: 
Create Date: 2026-05-06 20:54:54.869444
"""
from alembic import op
import sqlalchemy as sa


revision = '3215f2e07c9e'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
