#!/bin/bash
# Script to list ONLY important project files for Claude upload
# Filters out test files, scripts, duplicates, etc.

echo "📋 Listing IMPORTANT project files for Claude..."

# Output file
OUTPUT="important-files.txt"
> "$OUTPUT"

echo "=== BACKEND CORE ===" >> "$OUTPUT"
echo "./apps/flask-api/app.py" >> "$OUTPUT"
echo "./apps/flask-api/models.py" >> "$OUTPUT"
echo "./apps/flask-api/config.py" >> "$OUTPUT"
echo "./apps/flask-api/seed.py" >> "$OUTPUT"
echo "./apps/flask-api/migrations.py" >> "$OUTPUT"
echo "./apps/flask-api/metrics.py" >> "$OUTPUT"
echo "./apps/flask-api/wsgi.py" >> "$OUTPUT"
echo "./apps/flask-api/requirements.txt" >> "$OUTPUT"
echo "./apps/flask-api/alembic.ini" >> "$OUTPUT"
echo "./apps/flask-api/pytest.ini" >> "$OUTPUT"
echo "" >> "$OUTPUT"

echo "=== BACKEND ROUTES ===" >> "$OUTPUT"
echo "./apps/flask-api/routes/__init__.py" >> "$OUTPUT"
echo "./apps/flask-api/routes/auth.py" >> "$OUTPUT"
echo "./apps/flask-api/routes/admission.py" >> "$OUTPUT"
echo "./apps/flask-api/routes/career.py" >> "$OUTPUT"
echo "./apps/flask-api/routes/opportunities.py" >> "$OUTPUT"
echo "./apps/flask-api/routes/users.py" >> "$OUTPUT"
echo "./apps/flask-api/routes/notifications.py" >> "$OUTPUT"
echo "./apps/flask-api/routes/docs.py" >> "$OUTPUT"
echo "" >> "$OUTPUT"

echo "=== BACKEND MIGRATIONS ===" >> "$OUTPUT"
echo "./apps/flask-api/migrations/env.py" >> "$OUTPUT"
echo "" >> "$OUTPUT"

echo "=== BACKEND DATA ===" >> "$OUTPUT"
echo "./apps/flask-api/data/seed-programs.json" >> "$OUTPUT"
echo "./apps/flask-api/data/seed-career-paths.json" >> "$OUTPUT"
echo "./apps/flask-api/data/seed-opportunities.json" >> "$OUTPUT"
echo "" >> "$OUTPUT"

echo "=== FRONTEND CORE ===" >> "$OUTPUT"
echo "./apps/kiu-portal/package.json" >> "$OUTPUT"
echo "./apps/kiu-portal/vite.config.ts" >> "$OUTPUT"
echo "./apps/kiu-portal/tsconfig.json" >> "$OUTPUT"
echo "./apps/kiu-portal/index.html" >> "$OUTPUT"
echo "./apps/kiu-portal/components.json" >> "$OUTPUT"
echo "" >> "$OUTPUT"

echo "=== FRONTEND SRC ===" >> "$OUTPUT"
echo "./apps/kiu-portal/src/App.tsx" >> "$OUTPUT"
echo "./apps/kiu-portal/src/main.tsx" >> "$OUTPUT"
echo "./apps/kiu-portal/src/index.css" >> "$OUTPUT"
echo "" >> "$OUTPUT"

echo "=== FRONTEND SERVICES ===" >> "$OUTPUT"
echo "./apps/kiu-portal/src/services/api.ts" >> "$OUTPUT"
echo "./apps/kiu-portal/src/types/api.ts" >> "$OUTPUT"
echo "" >> "$OUTPUT"

echo "=== FRONTEND LIB ===" >> "$OUTPUT"
echo "./apps/kiu-portal/src/lib/utils.ts" >> "$OUTPUT"
echo "./apps/kiu-portal/src/lib/is-public-path.ts" >> "$OUTPUT"
echo "./apps/kiu-portal/src/lib/fetch-patch.ts" >> "$OUTPUT"
echo "" >> "$OUTPUT"

echo "=== FRONTEND HOOKS ===" >> "$OUTPUT"
echo "./apps/kiu-portal/src/hooks/use-toast.ts" >> "$OUTPUT"
echo "./apps/kiu-portal/src/hooks/use-mobile.tsx" >> "$OUTPUT"
echo "" >> "$OUTPUT"

echo "=== FRONTEND PAGES - AUTH ===" >> "$OUTPUT"
echo "./apps/kiu-portal/src/pages/auth/login.tsx" >> "$OUTPUT"
echo "./apps/kiu-portal/src/pages/auth/register.tsx" >> "$OUTPUT"
echo "./apps/kiu-portal/src/pages/auth/verify-otp.tsx" >> "$OUTPUT"
echo "./apps/kiu-portal/src/pages/auth/forgot-password.tsx" >> "$OUTPUT"
echo "./apps/kiu-portal/src/pages/auth/reset-password.tsx" >> "$OUTPUT"
echo "" >> "$OUTPUT"

echo "=== FRONTEND PAGES - MAIN ===" >> "$OUTPUT"
echo "./apps/kiu-portal/src/pages/home.tsx" >> "$OUTPUT"
echo "./apps/kiu-portal/src/pages/not-found.tsx" >> "$OUTPUT"
echo "" >> "$OUTPUT"

echo "=== FRONTEND PAGES - APPLICANT ===" >> "$OUTPUT"
echo "./apps/kiu-portal/src/pages/applicant/dashboard.tsx" >> "$OUTPUT"
echo "./apps/kiu-portal/src/pages/applicant/apply.tsx" >> "$OUTPUT"
echo "./apps/kiu-portal/src/pages/applicant/new-applicant.tsx" >> "$OUTPUT"
echo "" >> "$OUTPUT"

echo "=== FRONTEND PAGES - FINALIST ===" >> "$OUTPUT"
echo "./apps/kiu-portal/src/pages/finalist/dashboard.tsx" >> "$OUTPUT"
echo "./apps/kiu-portal/src/pages/finalist/career-paths.tsx" >> "$OUTPUT"
echo "./apps/kiu-portal/src/pages/finalist/opportunities.tsx" >> "$OUTPUT"
echo "" >> "$OUTPUT"

echo "=== FRONTEND PAGES - ADMIN ===" >> "$OUTPUT"
echo "./apps/kiu-portal/src/pages/admin/dashboard.tsx" >> "$OUTPUT"
echo "./apps/kiu-portal/src/pages/admin/admissions.tsx" >> "$OUTPUT"
echo "./apps/kiu-portal/src/pages/admin/opportunities.tsx" >> "$OUTPUT"
echo "" >> "$OUTPUT"

echo "=== FRONTEND COMPONENTS ===" >> "$OUTPUT"
echo "./apps/kiu-portal/src/components/layout.tsx" >> "$OUTPUT"
echo "./apps/kiu-portal/src/components/role-guard.tsx" >> "$OUTPUT"
echo "./apps/kiu-portal/src/components/error-boundary.tsx" >> "$OUTPUT"
echo "" >> "$OUTPUT"

echo "=== SHARED LIBRARY ===" >> "$OUTPUT"
echo "./lib/api-client-react/src/index.ts" >> "$OUTPUT"
echo "./lib/api-client-react/package.json" >> "$OUTPUT"
echo "./lib/api-client-react/tsconfig.json" >> "$OUTPUT"
echo "" >> "$OUTPUT"

echo "=== CONFIGURATION ===" >> "$OUTPUT"
echo "./package.json" >> "$OUTPUT"
echo "./pnpm-workspace.yaml" >> "$OUTPUT"
echo "./pyproject.toml" >> "$OUTPUT"
echo "./tsconfig.json" >> "$OUTPUT"
echo "./tsconfig.base.json" >> "$OUTPUT"
echo "./.env.example" >> "$OUTPUT"
echo "./.gitignore" >> "$OUTPUT"
echo "./.npmrc" >> "$OUTPUT"
echo "" >> "$OUTPUT"

echo "=== DOCUMENTATION ===" >> "$OUTPUT"
echo "./README.md" >> "$OUTPUT"
echo "./DEPLOYMENT.md" >> "$OUTPUT"
echo "./IMPLEMENTATION_PLAN.md" >> "$OUTPUT"
echo "./IMPLEMENTATION_PHASE2.md" >> "$OUTPUT"
echo "./IMPLEMENTATION_PHASE3.md" >> "$OUTPUT"
echo "./CHANGES.md" >> "$OUTPUT"

echo ""
echo "✅ Created $OUTPUT with important files only"
echo ""
echo "📊 Summary:"
grep -c "^===" "$OUTPUT" | xargs -I {} echo "   Total sections: {}"
grep -c "^\./" "$OUTPUT" | xargs -I {} echo "   Total files: {}"
echo ""
echo "💡 View the file: cat $OUTPUT"